import unittest
from parseFICG_functions import *

class test_parseFICG_functions(unittest.TestCase):
    def test_is_type_line(self):
        self.assertTrue(is_type_line('Tribal Enchantment — Hellion'))
        self.assertTrue(is_type_line('Creature — Rabbit'))
        self.assertTrue(is_type_line('Creature— Rabbit'))
        self.assertTrue(is_type_line('Instant'))
        self.assertTrue(is_type_line('Instant — Trap'))
        self.assertTrue(is_type_line('(WUBRG) Instant'))
        self.assertTrue(is_type_line('Legendary Instant'))
        self.assertTrue(is_type_line('Snow Instant'))
        self.assertTrue(is_type_line('Tribal Instant — Rabbit'))
        self.assertTrue(is_type_line('Trope Instant'))
        self.assertTrue(is_type_line('Instant // Instant'))
        self.assertTrue(is_type_line('Instant // Sorcery'))
        self.assertTrue(is_type_line('Sorcery // Instant'))
        self.assertTrue(is_type_line('Instant//Instant'))
        self.assertTrue(is_type_line('Sorcery'))
        self.assertTrue(is_type_line('Legendary Sorcery'))
        self.assertTrue(is_type_line('Snow Sorcery'))
        self.assertTrue(is_type_line('Tribal Sorcery — Hydra'))
        self.assertTrue(is_type_line('Sorcery // Sorcery'))
        self.assertTrue(is_type_line('Sorcery//Sorcery'))
        self.assertTrue(is_type_line('Enchantment'))
        self.assertTrue(is_type_line('Legendary Enchantment'))
        self.assertTrue(is_type_line('Snow Enchantment'))
        self.assertTrue(is_type_line('World Enchantment'))
        self.assertTrue(is_type_line('(WUBRG) Enchantment'))
        self.assertTrue(is_type_line('Enchantment Creature — Rabbit Avatar'))
        self.assertTrue(is_type_line('Enchantment Artifact'))
        self.assertTrue(is_type_line('Legendary Enchantment Creature — Rabbit'))
        self.assertTrue(is_type_line('Enchantment — Aura'))
        self.assertTrue(is_type_line('Artifact'))
        self.assertTrue(is_type_line('Artifact — Equipment'))
        self.assertTrue(is_type_line('Legendary Artifact'))
        self.assertTrue(is_type_line('Snow Artifact'))
        self.assertTrue(is_type_line('Artifact Creature — Rabbit Golem'))
        self.assertTrue(is_type_line('Legendary Artifact Creature — Rabbit'))
        self.assertTrue(is_type_line('Legendary Enchantment Artifact'))
        self.assertTrue(is_type_line('Enchantment Artifact'))
        self.assertTrue(is_type_line('World Artifact'))
        self.assertTrue(is_type_line('Tribal Artifact — Elf'))
        self.assertTrue(is_type_line('Conspiracy'))
        self.assertTrue(is_type_line('Plane — Example'))
        self.assertTrue(is_type_line('Scheme'))
        self.assertTrue(is_type_line('Ongoing Scheme'))
        self.assertTrue(is_type_line('Basic Land'))
        self.assertTrue(is_type_line('Land'))
        self.assertTrue(is_type_line('Land — Example'))
        self.assertTrue(is_type_line('Legendary Land'))
        self.assertTrue(is_type_line('Snow Land'))
        self.assertTrue(is_type_line('Planeswalker — Example'))
        self.assertTrue(is_type_line('Legendary Snow Creature — Spirit'))
        self.assertTrue(is_type_line('Phenomenon'))

        self.assertFalse(is_type_line('Legendary'))
        self.assertFalse(is_type_line('Legendary Example'))
        self.assertFalse(is_type_line('Snow'))
        self.assertFalse(is_type_line('Snow Example'))
        self.assertFalse(is_type_line('Tribal'))
        self.assertFalse(is_type_line('Tribal Instant'))
        self.assertFalse(is_type_line('Creature'))
        self.assertFalse(is_type_line('Instant 0'))
        self.assertFalse(is_type_line('Instant 1'))
        self.assertFalse(is_type_line('Instant 10'))
        self.assertFalse(is_type_line('Instant 1W'))
        self.assertFalse(is_type_line('Instant XX'))
        self.assertFalse(is_type_line('Instant (ub)'))
        self.assertFalse(is_type_line('Instant 1WUBRG'))
        self.assertFalse(is_type_line('Instant.'))
        self.assertFalse(is_type_line('Instantiate'))
        self.assertFalse(is_type_line('Example Sorcery'))
        self.assertFalse(is_type_line('Example Enchantment'))
        self.assertFalse(is_type_line('Enchantment Example'))
        self.assertFalse(is_type_line('Example Artifact'))
        self.assertFalse(is_type_line('Artifact Example'))
        self.assertFalse(is_type_line('Example Conspiracy'))
        self.assertFalse(is_type_line('Plane'))
        self.assertFalse(is_type_line('Example Scheme'))
        self.assertFalse(is_type_line('Example Land'))
        self.assertFalse(is_type_line('Planeswalker'))
        self.assertFalse(is_type_line('Example Phenomenon'))
        self.assertFalse(is_type_line('Phenomenon Example'))

unittest.main()
